### PR TITLE
Fix parsing of adb install/uninstall result

### LINKED ISSUE #18: "panic: runtime error: index out of range" on app upgrade
On each app upgrade I get this error:

```
$ fdroidcl upgrade com.nutomic.syncthingandroid
Downloading http://f-droid.org/repo/com.nutomic.syncthingandroid_103.apk... done
Upgrading com.nutomic.syncthingandroid... panic: runtime error: index out of range

goroutine 1 [running]:
panic(0x8147a0, 0xc82000e100)
    /usr/lib/golang/src/runtime/panic.go:481 +0x3e6
github.com/mvdan/fdroidcl/adb.getFailureCode(0xc820082320, 0x0, 0x0, 0x0, 0x0)
    /home/relan/opt/golang/src/github.com/mvdan/fdroidcl/adb/device.go:117 +0x78
github.com/mvdan/fdroidcl/adb.(*Device).install(0xc8200c2770, 0xc820e47a98, 0x1, 0x1, 0xc820a59860, 0x45, 0x0, 0x0)
    /home/relan/opt/golang/src/github.com/mvdan/fdroidcl/adb/device.go:157 +0x2b1
github.com/mvdan/fdroidcl/adb.(*Device).Upgrade(0xc8200c2770, 0xc820a59860, 0x45, 0x0, 0x0)
    /home/relan/opt/golang/src/github.com/mvdan/fdroidcl/adb/device.go:165 +0x94
main.upgradeApk(0xc8200c2770, 0xc820940000, 0xc820a59860, 0x45)
    /home/relan/opt/golang/src/github.com/mvdan/fdroidcl/cmd/fdroidcl/upgrade.go:48 +0x143
main.downloadAndDo(0xc82002a000, 0x1, 0x1, 0xc8200c2770, 0x95b4b8)
    /home/relan/opt/golang/src/github.com/mvdan/fdroidcl/cmd/fdroidcl/install.go:53 +0x37d
main.runUpgrade(0xc82000a3e0, 0x1, 0x1)
    /home/relan/opt/golang/src/github.com/mvdan/fdroidcl/cmd/fdroidcl/upgrade.go:43 +0x522
main.main()
    /home/relan/opt/golang/src/github.com/mvdan/fdroidcl/cmd/fdroidcl/main.go:180 +0x3fb
```

App is actually upgraded. This may be related to the adb version (Platform-tools 24.0.3):

```
Android Debug Bridge version 1.0.36
Revision e02fe72a18c3-android
```

Target device is Nexus 9, Android 7.0 (NRD90R). Host is Fedora 24 x86-64. I use adb from the official SDK, not from Fedora repositories. fdroidcl from master @ 4d0eeea.

### PR DESCRIPTION
**Pull request by relan**
Address various issues with adb output parsing.

Fixes #18.

### CODE REVIEW

File: adb/device.go [hunk 1]
```diff
@@ -165,13 +161,14 @@ func (d *Device) Upgrade(path string) error {
...
 
-func getResultLine(out io.Reader) string {
-	scanner := bufio.NewScanner(out)
-	for scanner.Scan() {
-		l := scanner.Text()
-		if strings.HasPrefix(l, "Failure") || strings.HasPrefix(l, "Success") {
-			return l
-		}
+func getResultLine(output []byte) string {
+	str := strings.TrimRight(string(output[:]), "\n")
```
Comment (mvdan) [inline adb/device.go]: Why `output[:]`? When you convert to string, the underlying data is already copied.

Also note that the previous method read line by line until one was found that matched what we were looking for. This is different; it will break if `adb` returns multiple lines. I've had this happen in the past with warnings and such, and it will only get worse now that we're capturing all the output. So I'd rather iterate over the lines as before.

File: adb/device.go [hunk 2]
```diff
@@ -165,13 +161,14 @@ func (d *Device) Upgrade(path string) error {
...
+	if strings.HasPrefix(str, "Success") {
+		return str
+	}
+	fail := strings.Index(str, "Failure")
+	if fail >= 0 {
+		return str[fail:]
```
Comment (mvdan) [inline adb/device.go]: Why this index of Failure? If you do what I suggested above regarding reading line by line, you can just use `HasPrefix` like before.

File: adb/device.go (hunk 1 above)
Comment (relan) [inline adb/device.go]: Good point.

File: adb/device.go (hunk 2 above)
Comment (relan) [inline adb/device.go]: Because in some error messages "Failure" is not the first word in a line (see the OP).

**Comment by relan** [comment]
I've found that adb can print "Failure" without any error code string in [...], e.g. when you try to uninstall unexisting package:

```sh
$ adb uninstall asd
Failure
```

The whole idea of parsing adb output seems broken to me...

File: adb/device.go (hunk 2 above)
Comment (mvdan) [inline adb/device.go]: Ah, missed that. Thanks!

**Comment by mvdan** [comment]
> The whole idea of parsing adb output seems broken to me...

Sorry, what is this referencing? The slicing of the output `return str[fail:]`? If so, feel free to simply `return str`.

**Comment by mvdan** [comment]
@relan let me know if you don't have time to finish this off. Happy to merge and do the little fixes on top.

**Comment by relan** [comment]
I hope I'll have some time on Saturday or Sunday to finish this MR. I didn't abandon it.

**Comment by relan** [comment]
Marked as WIP because I'm going to fix the case when `adb uninstall` prints just `Failure` without an error string (`fdroidcl` crashes on them).

**Comment by mvdan** [comment]
@relan is this ready for review? I missed it as github doesn't notify me unless someone comments.

**Comment by relan** [comment]
Yep. Sorry, forgot to ping you.
